
var exchanges_3_static = 
{  
   "ise":{  
      "exchange":"ise",
      "source":"http://www.davy.ie",
      "time":"2018-03-18T23:04:55.702Z",
      "cached":false,
      "details":"http://www.davy.ie/markets-and-share-prices/iseq/detail?ric=",
      "data":[  
         {  
            "company":"ABBEY",
            "symbol":"ABBY_I",
            "price":"14.90",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"AIB GROUP PLC",
            "symbol":"AIBG_I",
            "price":"5.00",
            "change":"+0.16",
            "pChg":"+3.31%"
         },
         {  
            "company":"AMINEX",
            "symbol":"AMNX_I",
            "price":"0.029",
            "change":"-0.001",
            "pChg":"-3.33%"
         },
         {  
            "company":"AMRYT PHARMA",
            "symbol":"AMYT_I",
            "price":"0.24",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"APPLEGREEN PLC",
            "symbol":"APGNA_I",
            "price":"5.82",
            "change":"+0.02",
            "pChg":"+0.34%"
         },
         {  
            "company":"ARYZTA AG",
            "symbol":"ARYN_I",
            "price":"18.60",
            "change":"-0.41",
            "pChg":"-2.16%"
         },
         {  
            "company":"BK IRE GRP PLC",
            "symbol":"BIRG_I",
            "price":"7.275",
            "change":"+0.085",
            "pChg":"+1.18%"
         },
         {  
            "company":"C&C GROUP",
            "symbol":"GCC_I",
            "price":"2.73",
            "change":"-0.055",
            "pChg":"-1.97%"
         },
         {  
            "company":"CAIRN HOMES PLC",
            "symbol":"CRN_I",
            "price":"1.80",
            "change":"-0.08",
            "pChg":"-4.26%"
         },
         {  
            "company":"CPL RESOURCES",
            "symbol":"DQ5_I",
            "price":"6.40",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"CRH PLC",
            "symbol":"CRH_I",
            "price":"28.218",
            "change":"-0.102",
            "pChg":"-0.36%"
         },
         {  
            "company":"DALATA HOTEL GRP",
            "symbol":"DHG_I",
            "price":"6.44",
            "change":"+0.04",
            "pChg":"+0.62%"
         },
         {  
            "company":"DATALEX",
            "symbol":"DLE_I",
            "price":"3.00",
            "change":"+0.06",
            "pChg":"+2.04%"
         },
         {  
            "company":"DONEGAL INVST",
            "symbol":"DQ7_I",
            "price":"8.70",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"FBD HOLDINGS",
            "symbol":"FBD_I",
            "price":"12.50",
            "change":"-0.25",
            "pChg":"-1.96%"
         },
         {  
            "company":"FIRST DERIVATIVE",
            "symbol":"FRST_I",
            "price":"42.80",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"GLANBIA PLC",
            "symbol":"GL9_I",
            "price":"14.38",
            "change":"+0.12",
            "pChg":"+0.84%"
         },
         {  
            "company":"GLENVEAGH",
            "symbol":"GLV_I",
            "price":"1.107",
            "change":"-0.007",
            "pChg":"-0.63%"
         },
         {  
            "company":"GREAT WEST MIN",
            "symbol":"GWMO_I",
            "price":"0.012",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"GREEN REIT",
            "symbol":"GN1_I",
            "price":"1.50",
            "change":"-0.02",
            "pChg":"-1.32%"
         },
         {  
            "company":"GREENCOAT RENEWA",
            "symbol":"GRPG_I",
            "price":"1.06",
            "change":"+0.01",
            "pChg":"+0.95%"
         },
         {  
            "company":"GREENCOAT RENEWA",
            "symbol":"GRPG_I",
            "price":"1.06",
            "change":"+0.01",
            "pChg":"+0.95%"
         },
         {  
            "company":"HIBERNIA REIT",
            "symbol":"HBRN_I",
            "price":"1.43",
            "change":"-0.012",
            "pChg":"-0.83%"
         },
         {  
            "company":"HOSTELWORLD",
            "symbol":"HSW_I",
            "price":"4.70",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"IFG GROUP",
            "symbol":"IFG_I",
            "price":"2.06",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"INDEPENDENT NEWS",
            "symbol":"INME_I",
            "price":"0.099",
            "change":"+0.003",
            "pChg":"+3.12%"
         },
         {  
            "company":"IRISH CONT GP UN",
            "symbol":"IR5B_u_I",
            "price":"5.87",
            "change":"-0.13",
            "pChg":"-2.17%"
         },
         {  
            "company":"IRISH RES PR PLC",
            "symbol":"IRES_I",
            "price":"1.41",
            "change":"-0.016",
            "pChg":"-1.12%"
         },
         {  
            "company":"ISEQ OVERALL",
            "symbol":"_ISEQ",
            "price":"6,693.94",
            "change":"-13.82",
            "pChg":"-0.21%"
         },
         {  
            "company":"KENMARE RES",
            "symbol":"JEV_I",
            "price":"2.90",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"KERRY GROUP",
            "symbol":"KYGa_I",
            "price":"78.11",
            "change":"-1.44",
            "pChg":"-1.81%"
         },
         {  
            "company":"KINGSPAN GROUP",
            "symbol":"KSP_I",
            "price":"34.28",
            "change":"-0.32",
            "pChg":"-0.92%"
         },
         {  
            "company":"MAINSTAY MEDICAL",
            "symbol":"MSTY_I",
            "price":"15.60",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"MALIN CORP PLC",
            "symbol":"MLCM_I",
            "price":"7.75",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"MINCON GROUP PLC",
            "symbol":"MCON_I",
            "price":"1.20",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"ORIGIN ENTERPRIS",
            "symbol":"OGN_I",
            "price":"5.56",
            "change":"-0.07",
            "pChg":"-1.24%"
         },
         {  
            "company":"ORMONDE MINING",
            "symbol":"ORM_I",
            "price":"0.023",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"OVOCA GOLD",
            "symbol":"OVG_I",
            "price":"0.10",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"PADDY PW BETFAIR",
            "symbol":"PPB_I",
            "price":"86.80",
            "change":"-0.30",
            "pChg":"-0.34%"
         },
         {  
            "company":"PERMANENT TSB GP",
            "symbol":"IL0A_I",
            "price":"2.00",
            "change":"+0.004",
            "pChg":"+0.20%"
         },
         {  
            "company":"PETRONEFT RES",
            "symbol":"PTR_I",
            "price":"0.016",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"PROVIDENCE RES",
            "symbol":"PZQA_I",
            "price":"0.11",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"RYANAIR HLDGS",
            "symbol":"RYA_I",
            "price":"16.33",
            "change":"+0.10",
            "pChg":"+0.62%"
         },
         {  
            "company":"SMURFIT KAPPA",
            "symbol":"SKG_I",
            "price":"35.92",
            "change":"+0.42",
            "pChg":"+1.18%"
         },
         {  
            "company":"TOTAL PRODUCE",
            "symbol":"T7O_I",
            "price":"2.39",
            "change":"0.00",
            "pChg":"0.00%"
         },
         {  
            "company":"VR EDUCATION H.",
            "symbol":"VRE_I",
            "price":"0.14",
            "change":"-0.005",
            "pChg":"-3.45%"
         },
         {  
            "company":"ZAMANO",
            "symbol":"ZMNO_I",
            "price":"0.04",
            "change":"0.00",
            "pChg":"0.00%"
         }
      ]
   },
   "ftse350":{  
      "exchange":"ftse350",
      "source":"http://shares.telegraph.co.uk",
      "time":"2018-03-18T23:04:55.702Z",
      "cached":false,
      "details":"https://web.archive.org/web/20170526202357/http://shares.telegraph.co.uk:80/quote/?epic",
      "data":[  
         {  
            "company":"3i Infrastructure",
            "symbol":"3IN",
            "price":"196.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"AA",
            "symbol":"AA_",
            "price":"242.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Anglo American",
            "symbol":"AAL",
            "price":"1,100.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Associated British Foods",
            "symbol":"ABF",
            "price":"2,958.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Acacia Mining",
            "symbol":"ACA",
            "price":"280.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Admiral Group",
            "symbol":"ADM",
            "price":"2,056.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Aberdeen Asset Management",
            "symbol":"ADN",
            "price":"323.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Aggreko",
            "symbol":"AGK",
            "price":"862.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Assura Group",
            "symbol":"AGR",
            "price":"62.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ashtead Group",
            "symbol":"AHT",
            "price":"1,710.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Aldermore Group",
            "symbol":"ALD",
            "price":"228.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Amec Foster Wheeler",
            "symbol":"AMFW",
            "price":"448.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Antofagasta",
            "symbol":"ANTO",
            "price":"882.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ascential",
            "symbol":"ASCL",
            "price":"334.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ashmore Group",
            "symbol":"ASHM",
            "price":"362.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Aberforth Smaller Companies Trust",
            "symbol":"ASL",
            "price":"1,272.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Alliance Trust",
            "symbol":"ATST",
            "price":"721.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Auto Trader Group",
            "symbol":"AUTO",
            "price":"378.40",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Aviva",
            "symbol":"AV_",
            "price":"531.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"AVEVA Group",
            "symbol":"AVV",
            "price":"2,049.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"AstraZeneca",
            "symbol":"AZN",
            "price":"5,123.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"BAE Systems",
            "symbol":"BA_",
            "price":"613.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Babcock International Group",
            "symbol":"BAB",
            "price":"860.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Barr (A G)",
            "symbol":"BAG",
            "price":"594.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Barclays",
            "symbol":"BARC",
            "price":"208.23",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"British American Tobacco",
            "symbol":"BATS",
            "price":"5,423.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"BBA Aviation",
            "symbol":"BBA",
            "price":"309.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Tritax Big Box Reit",
            "symbol":"BBOX",
            "price":"146.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Balfour Beatty",
            "symbol":"BBY",
            "price":"274.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Barratt Developments",
            "symbol":"BDEV",
            "price":"610.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Beazley",
            "symbol":"BEZ",
            "price":"513.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"BGEO Group",
            "symbol":"BGEO",
            "price":"3,514.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Berkeley Group Holdings (The)",
            "symbol":"BKG",
            "price":"3,412.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"British Land Co",
            "symbol":"BLND",
            "price":"625.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"BHP Billiton",
            "symbol":"BLT",
            "price":"1,315.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"B&M; European Value Retail",
            "symbol":"BME",
            "price":"339.65",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Bankers' Investment Trust  (the)",
            "symbol":"BNKR",
            "price":"805.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Bunzl",
            "symbol":"BNZL",
            "price":"2,271.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Booker Group",
            "symbol":"BOK",
            "price":"193.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Bodycote",
            "symbol":"BOY",
            "price":"834.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"BP",
            "symbol":"BP_",
            "price":"450.20",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Burberry Group",
            "symbol":"BRBY",
            "price":"1,654.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Berendsen",
            "symbol":"BRSN",
            "price":"1,279.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Brewin Dolphin Holdings",
            "symbol":"BRW",
            "price":"349.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"BT Group",
            "symbol":"BT_A",
            "price":"310.83",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"British Empire Securities & General Trust",
            "symbol":"BTEM",
            "price":"694.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"BTG",
            "symbol":"BTG",
            "price":"667.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Britvic",
            "symbol":"BVIC",
            "price":"721.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Bovis Homes Group",
            "symbol":"BVS",
            "price":"960.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Brown (N) Group",
            "symbol":"BWNG",
            "price":"296.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Bellway",
            "symbol":"BWY",
            "price":"3,113.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Big Yellow Group",
            "symbol":"BYG",
            "price":"786.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Capital & Counties Properties",
            "symbol":"CAPC",
            "price":"311.10",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Card Factory",
            "symbol":"CARD",
            "price":"298.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Close Brothers Group",
            "symbol":"CBG",
            "price":"1,500.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Computacenter",
            "symbol":"CCC",
            "price":"881.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Coca-Cola HBC",
            "symbol":"CCH",
            "price":"2,274.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Carnival",
            "symbol":"CCL",
            "price":"5,177.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Centamin",
            "symbol":"CEY",
            "price":"162.80",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Cineworld Group",
            "symbol":"CINE",
            "price":"695.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Clarkson",
            "symbol":"CKN",
            "price":"2,669.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Caledonia Investments",
            "symbol":"CLDN",
            "price":"2,839.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"CLS Holdings",
            "symbol":"CLI",
            "price":"206.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Carillion",
            "symbol":"CLLN",
            "price":"64.33",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Centrica",
            "symbol":"CNA",
            "price":"207.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Cairn Energy",
            "symbol":"CNE",
            "price":"175.10",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Coats Group",
            "symbol":"COA",
            "price":"76.93",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Cobham",
            "symbol":"COB",
            "price":"133.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Compass Group",
            "symbol":"CPG",
            "price":"1,628.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Capita Group (The)",
            "symbol":"CPI",
            "price":"679.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Croda International",
            "symbol":"CRDA",
            "price":"3,908.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"CRH",
            "symbol":"CRH",
            "price":"2,754.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Crest Nicholson Holdings",
            "symbol":"CRST",
            "price":"538.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Countryside Properties",
            "symbol":"CSP",
            "price":"364.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"ConvaTec Group",
            "symbol":"CTEC",
            "price":"308.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"City Of London Investment Trust  (the)",
            "symbol":"CTY",
            "price":"430.90",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Cranswick",
            "symbol":"CWK",
            "price":"2,829.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"CYBG",
            "symbol":"CYBG",
            "price":"276.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Dixons Carphone",
            "symbol":"DC_",
            "price":"270.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"DCC",
            "symbol":"DCC",
            "price":"7,077.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Dairy Crest Group",
            "symbol":"DCG",
            "price":"601.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Diageo",
            "symbol":"DGE",
            "price":"2,309.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Daejan Holdings",
            "symbol":"DJAN",
            "price":"6,375.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Direct Line Insurance Group",
            "symbol":"DLG",
            "price":"373.60",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Derwent London",
            "symbol":"DLN",
            "price":"2,826.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Dunelm Group",
            "symbol":"DNLM",
            "price":"588.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Domino's Pizza Group",
            "symbol":"DOM",
            "price":"280.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Dechra Pharmaceuticals",
            "symbol":"DPH",
            "price":"1,730.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Diploma",
            "symbol":"DPLM",
            "price":"1,062.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Drax Group",
            "symbol":"DRX",
            "price":"324.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Dignity",
            "symbol":"DTY",
            "price":"2,525.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Electrocomponents",
            "symbol":"ECM",
            "price":"623.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Edinburgh Investment Trust  (the)",
            "symbol":"EDIN",
            "price":"753.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Elementis",
            "symbol":"ELM",
            "price":"305.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Electra Private Equity",
            "symbol":"ELTA",
            "price":"1,681.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Man Group",
            "symbol":"EMG",
            "price":"154.80",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Euromoney Institutional Investor",
            "symbol":"ERM",
            "price":"1,105.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Essentra",
            "symbol":"ESNT",
            "price":"561.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"esure Group",
            "symbol":"ESUR",
            "price":"296.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Entertainment One Group",
            "symbol":"ETO",
            "price":"242.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Evraz",
            "symbol":"EVR",
            "price":"228.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Experian",
            "symbol":"EXPN",
            "price":"1,538.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"easyJet",
            "symbol":"EZJ",
            "price":"1,333.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"F&C; Commercial Property Tst Ld",
            "symbol":"FCPT",
            "price":"146.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Fidelity China Special Situations",
            "symbol":"FCSS",
            "price":"215.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"FDM Group (Holdings)",
            "symbol":"FDM",
            "price":"761.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Fidessa Group",
            "symbol":"FDSA",
            "price":"2,361.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Fidelity European Values",
            "symbol":"FEV",
            "price":"221.10",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"FirstGroup",
            "symbol":"FGP",
            "price":"117.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Finsbury Growth & Income Trust",
            "symbol":"FGT",
            "price":"725.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Foreign & Colonial Investment Trust",
            "symbol":"FRCL",
            "price":"604.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Fresnillo",
            "symbol":"FRES",
            "price":"1,530.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Fisher (James) & Sons",
            "symbol":"FSJ",
            "price":"1,589.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ferrexpo",
            "symbol":"FXPO",
            "price":"217.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"GCP Infrastructure Investments",
            "symbol":"GCP",
            "price":"125.80",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Galliford Try",
            "symbol":"GFRD",
            "price":"1,325.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"G4S",
            "symbol":"GFS",
            "price":"340.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Grafton Group",
            "symbol":"GFTU",
            "price":"737.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"GKN",
            "symbol":"GKN",
            "price":"332.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Glencore",
            "symbol":"GLEN",
            "price":"318.78",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Greencore Group",
            "symbol":"GNC",
            "price":"228.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Greene King",
            "symbol":"GNK",
            "price":"683.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Genus",
            "symbol":"GNS",
            "price":"1,733.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Go-Ahead Group (The)",
            "symbol":"GOG",
            "price":"1,775.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Great Portland Estates",
            "symbol":"GPOR",
            "price":"616.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Greggs",
            "symbol":"GRG",
            "price":"1,092.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Grainger",
            "symbol":"GRI",
            "price":"268.10",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"GlaxoSmithKline",
            "symbol":"GSK",
            "price":"1,625.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Genesis Emerging Markets Fnd Ld",
            "symbol":"GSS",
            "price":"680.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"GVC Holdings",
            "symbol":"GVC",
            "price":"765.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hays",
            "symbol":"HAS",
            "price":"168.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Halfords Group",
            "symbol":"HFD",
            "price":"334.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"HICL Infrastructure Co",
            "symbol":"HICL",
            "price":"159.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hikma Pharmaceuticals",
            "symbol":"HIK",
            "price":"1,380.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hill & Smith Holdings",
            "symbol":"HILS",
            "price":"1,377.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hargreaves Lansdown",
            "symbol":"HL_",
            "price":"1,345.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Halma",
            "symbol":"HLMA",
            "price":"1,092.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hammerson",
            "symbol":"HMSO",
            "price":"595.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hochschild Mining",
            "symbol":"HOC",
            "price":"285.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"HSBC Holdings",
            "symbol":"HSBA",
            "price":"740.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hastings Group Holdings",
            "symbol":"HSTG",
            "price":"310.90",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hansteen Holdings",
            "symbol":"HSTN",
            "price":"128.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Homeserve",
            "symbol":"HSV",
            "price":"732.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hiscox",
            "symbol":"HSX",
            "price":"1,354.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Hunting",
            "symbol":"HTG",
            "price":"491.60",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Harbourvest Global Private Equity",
            "symbol":"HVPE",
            "price":"1,257.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Howden Joinery Group",
            "symbol":"HWDN",
            "price":"432.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"International Consolidated Airlines Group",
            "symbol":"IAG",
            "price":"595.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ibstock",
            "symbol":"IBST",
            "price":"244.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Intermediate Capital Group",
            "symbol":"ICP",
            "price":"906.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"IG Group Holdings",
            "symbol":"IGG",
            "price":"638.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"InterContinental Hotels Group",
            "symbol":"IHG",
            "price":"4,328.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"3i Group",
            "symbol":"III",
            "price":"927.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Imperial Brands",
            "symbol":"IMB",
            "price":"3,511.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"IMI",
            "symbol":"IMI",
            "price":"1,318.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Inchcape",
            "symbol":"INCH",
            "price":"776.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Indivior",
            "symbol":"INDV",
            "price":"320.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Informa",
            "symbol":"INF",
            "price":"678.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"International Public Partnership",
            "symbol":"INPP",
            "price":"160.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Intu Properties",
            "symbol":"INTU",
            "price":"278.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Investec",
            "symbol":"INVP",
            "price":"592.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"IP Group",
            "symbol":"IPO",
            "price":"140.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Inmarsat",
            "symbol":"ISAT",
            "price":"779.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Intertek Group",
            "symbol":"ITRK",
            "price":"4,343.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"ITV",
            "symbol":"ITV",
            "price":"178.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"IWG",
            "symbol":"IWG",
            "price":"322.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"JPMorgan American IT",
            "symbol":"JAM",
            "price":"387.60",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"JD Sports Fashion",
            "symbol":"JD_",
            "price":"359.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Wetherspoon (J D)",
            "symbol":"JDW",
            "price":"1,022.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Just Eat",
            "symbol":"JE_",
            "price":"697.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"JPMorgan Indian Investment Trust",
            "symbol":"JII",
            "price":"747.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"John Laing Group",
            "symbol":"JLG",
            "price":"307.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"John Laing Infrastructure Fund",
            "symbol":"JLIF",
            "price":"133.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Jardine Lloyd Thompson Group",
            "symbol":"JLT",
            "price":"1,189.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Johnson Matthey",
            "symbol":"JMAT",
            "price":"2,888.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"JPMorgan Emerging Markets Investment Trust",
            "symbol":"JMG",
            "price":"818.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Jupiter Fund Management",
            "symbol":"JUP",
            "price":"546.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Just Group  Ord 10p",
            "symbol":"JUST",
            "price":"135.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Kaz Minerals",
            "symbol":"KAZ",
            "price":"642.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Kingfisher",
            "symbol":"KGF",
            "price":"304.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Kier Group",
            "symbol":"KIE",
            "price":"1,288.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Kennedy Wilson Europe Real Estate",
            "symbol":"KWE",
            "price":"1,137.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Land Securities Group",
            "symbol":"LAND",
            "price":"1,032.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ladbrokes Coral Group",
            "symbol":"LCL",
            "price":"115.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Legal & General Group",
            "symbol":"LGEN",
            "price":"262.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Lloyds Banking Group  ORD",
            "symbol":"LLOY",
            "price":"68.67",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"LondonMetric Property",
            "symbol":"LMP",
            "price":"169.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Lancashire Holdings",
            "symbol":"LRE",
            "price":"718.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"London Stock Exchange Group",
            "symbol":"LSE",
            "price":"3,770.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Mitchells & Butlers",
            "symbol":"MAB",
            "price":"231.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Marston's",
            "symbol":"MARS",
            "price":"122.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Micro Focus International",
            "symbol":"MCRO",
            "price":"2,254.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Mccarthy Stone",
            "symbol":"MCS",
            "price":"180.40",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Mediclinic International",
            "symbol":"MDC",
            "price":"739.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Merlin Entertainments",
            "symbol":"MERL",
            "price":"474.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Morgan Advanced Materials",
            "symbol":"MGAM",
            "price":"299.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Meggitt",
            "symbol":"MGGT",
            "price":"499.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Marks & Spencer Group",
            "symbol":"MKS",
            "price":"331.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Millennium & Copthorne Hotels",
            "symbol":"MLC",
            "price":"453.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Mondi",
            "symbol":"MNDI",
            "price":"2,046.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Monks Investment Trust  (the)",
            "symbol":"MNKS",
            "price":"703.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Moneysupermarket.com Group",
            "symbol":"MONY",
            "price":"350.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Mercantile Inv Tst",
            "symbol":"MRC",
            "price":"1,971.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Melrose",
            "symbol":"MRO",
            "price":"231.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Morrison (Wm) Supermarkets",
            "symbol":"MRW",
            "price":"249.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Marshalls",
            "symbol":"MSLH",
            "price":"370.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"MITIE Group",
            "symbol":"MTO",
            "price":"273.70",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Metro Bank",
            "symbol":"MTRO",
            "price":"3,574.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Murray International Trust",
            "symbol":"MYI",
            "price":"1,256.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"NB Global Floating Rate Inc Fund £",
            "symbol":"NBLS",
            "price":"94.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"National Express Group",
            "symbol":"NEX",
            "price":"362.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"National Grid",
            "symbol":"NG_",
            "price":"955.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"NMC Health",
            "symbol":"NMC",
            "price":"2,232.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Nostrum Oil & Gas",
            "symbol":"NOG",
            "price":"428.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"NewRiver Retail",
            "symbol":"NRR",
            "price":"350.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Northgate",
            "symbol":"NTG",
            "price":"434.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"NEX Group",
            "symbol":"NXG",
            "price":"668.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Next",
            "symbol":"NXT",
            "price":"3,781.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ocado Group",
            "symbol":"OCDO",
            "price":"298.65",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Old Mutual Group",
            "symbol":"OML",
            "price":"200.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Onesavings Bank",
            "symbol":"OSB",
            "price":"397.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"P2P Global Investments",
            "symbol":"P2P",
            "price":"876.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Paragon Group of Companies (The)",
            "symbol":"PAG",
            "price":"418.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"PageGroup",
            "symbol":"PAGE",
            "price":"490.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"PayPoint",
            "symbol":"PAY",
            "price":"861.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Paysafe Group",
            "symbol":"PAYS",
            "price":"542.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Polar Capital Technology Trust",
            "symbol":"PCT",
            "price":"1,038.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Petra Diamonds",
            "symbol":"PDL",
            "price":"109.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Pets At Home Group",
            "symbol":"PETS",
            "price":"159.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Petrofac",
            "symbol":"PFC",
            "price":"470.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Provident Financial",
            "symbol":"PFG",
            "price":"2,390.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Phoenix Group Holdings",
            "symbol":"PHNX",
            "price":"760.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Perpetual Income And Growth Investment Trust",
            "symbol":"PLI",
            "price":"395.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Polypipe Group",
            "symbol":"PLP",
            "price":"398.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Personal Assets Trust",
            "symbol":"PNL",
            "price":"41,010.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Pennon Group",
            "symbol":"PNN",
            "price":"826.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Polymetal International",
            "symbol":"POLY",
            "price":"906.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Paddy Power Betfair",
            "symbol":"PPB",
            "price":"7,700.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Prudential",
            "symbol":"PRU",
            "price":"1,787.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Pershing Square Holdings  Ord Npv",
            "symbol":"PSH",
            "price":"1,082.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Persimmon",
            "symbol":"PSN",
            "price":"2,461.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Pearson",
            "symbol":"PSON",
            "price":"642.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Playtech",
            "symbol":"PTEC",
            "price":"965.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"PZ Cussons",
            "symbol":"PZC",
            "price":"363.60",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"QinetiQ Group",
            "symbol":"QQ_",
            "price":"242.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Rathbone Brothers",
            "symbol":"RAT",
            "price":"2,624.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Reckitt Benckiser Group",
            "symbol":"RB_",
            "price":"7,952.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Royal Bank of Scotland Group (The)",
            "symbol":"RBS",
            "price":"249.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"RIT Capital Partners",
            "symbol":"RCP",
            "price":"1,941.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Redefine International",
            "symbol":"RDI",
            "price":"38.74",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Royal Dutch Shell",
            "symbol":"RDSA",
            "price":"2,093.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Royal Dutch Shell",
            "symbol":"RDSB",
            "price":"2,111.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Redrow",
            "symbol":"RDW",
            "price":"583.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"RELX",
            "symbol":"REL",
            "price":"1,655.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Rio Tinto",
            "symbol":"RIO",
            "price":"3,386.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Royal Mail",
            "symbol":"RMG",
            "price":"398.20",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Rightmove",
            "symbol":"RMV",
            "price":"4,306.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Rank Group (The)",
            "symbol":"RNK",
            "price":"223.70",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Rotork",
            "symbol":"ROR",
            "price":"249.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"RPC Group",
            "symbol":"RPC",
            "price":"891.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Rolls-Royce Group",
            "symbol":"RR_",
            "price":"917.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Randgold Resources",
            "symbol":"RRS",
            "price":"6,987.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"RSA Insurance Group",
            "symbol":"RSA",
            "price":"647.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Riverstone Energy Limited",
            "symbol":"RSE",
            "price":"1,265.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Renishaw",
            "symbol":"RSW",
            "price":"3,938.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Restaurant Group (The)",
            "symbol":"RTN",
            "price":"328.70",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Rentokil Initial",
            "symbol":"RTO",
            "price":"279.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Safestore Holdings",
            "symbol":"SAFE",
            "price":"428.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Saga",
            "symbol":"SAGA",
            "price":"210.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Sainsbury (J)",
            "symbol":"SBRY",
            "price":"248.65",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Scottish Investment Trust  (the)",
            "symbol":"SCIN",
            "price":"821.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Softcat",
            "symbol":"SCT",
            "price":"382.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Schroders",
            "symbol":"SDR",
            "price":"3,353.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Stagecoach Group",
            "symbol":"SGC",
            "price":"181.30",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Sage Group (The)",
            "symbol":"SGE",
            "price":"691.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"SuperGroup",
            "symbol":"SGP",
            "price":"1,464.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Segro",
            "symbol":"SGRO",
            "price":"510.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Shaftesbury",
            "symbol":"SHB",
            "price":"984.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"SIG",
            "symbol":"SHI",
            "price":"158.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Shire",
            "symbol":"SHP",
            "price":"4,081.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Smurfit Kappa Group",
            "symbol":"SKG",
            "price":"2,355.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Sky",
            "symbol":"SKY",
            "price":"970.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Standard Life",
            "symbol":"SL_",
            "price":"428.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Smith (DS)",
            "symbol":"SMDS",
            "price":"485.10",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Smiths Group",
            "symbol":"SMIN",
            "price":"1,608.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"St Modwen Properties",
            "symbol":"SMP",
            "price":"355.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Scottish Mortgage Investment Trust",
            "symbol":"SMT",
            "price":"410.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"WH Smith",
            "symbol":"SMWH",
            "price":"1,700.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Smith & Nephew",
            "symbol":"SN_",
            "price":"1,333.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Sanne Group",
            "symbol":"SNN",
            "price":"678.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Senior",
            "symbol":"SNR",
            "price":"239.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Sophos Group",
            "symbol":"SOPH",
            "price":"469.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Sports Direct International",
            "symbol":"SPD",
            "price":"335.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Spire Healthcare Group",
            "symbol":"SPI",
            "price":"345.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Spirax-Sarco Engineering",
            "symbol":"SPX",
            "price":"5,622.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Serco Group",
            "symbol":"SRP",
            "price":"112.60",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"SSE",
            "symbol":"SSE",
            "price":"1,476.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"SSP Group",
            "symbol":"SSPG",
            "price":"494.60",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Standard Chartered",
            "symbol":"STAN",
            "price":"825.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"St James's Place",
            "symbol":"STJ",
            "price":"1,231.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Stobart Group",
            "symbol":"STOB",
            "price":"287.70",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Savills",
            "symbol":"SVS",
            "price":"901.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Severn Trent",
            "symbol":"SVT",
            "price":"2,265.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Spectris",
            "symbol":"SXS",
            "price":"2,607.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Sirius Minerals",
            "symbol":"SXX",
            "price":"30.66",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Synchronica",
            "symbol":"SYNC",
            "price":"171.90",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Synthomer",
            "symbol":"SYNT",
            "price":"488.05",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"TalkTalk Telecom Group",
            "symbol":"TALK",
            "price":"184.15",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Tate & Lyle",
            "symbol":"TATE",
            "price":"678.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"TBC Bank Group",
            "symbol":"TBCG",
            "price":"1,649.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"TP Icap",
            "symbol":"TCAP",
            "price":"478.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Thomas Cook Group",
            "symbol":"TCG",
            "price":"99.98",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ted Baker",
            "symbol":"TED",
            "price":"2,458.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Templeton Emerging Markets Investment Trust",
            "symbol":"TEM",
            "price":"717.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Telecom plus",
            "symbol":"TEP",
            "price":"1,125.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Tullow Oil",
            "symbol":"TLW",
            "price":"154.35",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Temple Bar Investment Trust",
            "symbol":"TMPL",
            "price":"1,274.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Travis Perkins",
            "symbol":"TPK",
            "price":"1,468.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"The Renewables Infrastructure Group",
            "symbol":"TRIG",
            "price":"109.55",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"TR Property Investment Trust",
            "symbol":"TRY",
            "price":"349.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Tesco",
            "symbol":"TSCO",
            "price":"175.45",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"TUI AG",
            "symbol":"TUI",
            "price":"1,211.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Taylor Wimpey",
            "symbol":"TW_",
            "price":"185.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"UBM",
            "symbol":"UBM",
            "price":"695.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"UDG Healthcare",
            "symbol":"UDG",
            "price":"842.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"UK Commercial Property Trust",
            "symbol":"UKCM",
            "price":"90.13",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Ultra Electronics Holdings",
            "symbol":"ULE",
            "price":"2,032.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Unilever",
            "symbol":"ULVR",
            "price":"4,388.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Unite Group",
            "symbol":"UTG",
            "price":"671.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"United Utilities Group",
            "symbol":"UU_",
            "price":"897.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Victrex",
            "symbol":"VCT",
            "price":"1,908.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Vectura Group",
            "symbol":"VEC",
            "price":"113.40",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Vedanta Resources",
            "symbol":"VED",
            "price":"728.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Vietnam Enterprise Investments",
            "symbol":"VEIL",
            "price":"381.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Virgin Money Holdings UK",
            "symbol":"VM_",
            "price":"311.75",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Vodafone Group",
            "symbol":"VOD",
            "price":"224.85",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Vesuvius",
            "symbol":"VSVS",
            "price":"599.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Weir Group",
            "symbol":"WEIR",
            "price":"1,911.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"John Wood Group",
            "symbol":"WG_",
            "price":"616.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Wizz Air Holdings",
            "symbol":"WIZZ",
            "price":"2,610.50",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Workspace Group",
            "symbol":"WKP",
            "price":"894.25",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"William Hill",
            "symbol":"WMH",
            "price":"248.80",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Wolseley",
            "symbol":"WOS",
            "price":"4,585.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Woodford Patient Capital Trust",
            "symbol":"WPCT",
            "price":"105.70",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Worldpay Group",
            "symbol":"WPG",
            "price":"377.95",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"WPP Group",
            "symbol":"WPP",
            "price":"1,591.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Witan Investment Trust",
            "symbol":"WTAN",
            "price":"1,033.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Whitbread",
            "symbol":"WTB",
            "price":"3,927.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Worldwide Healthcare Trust",
            "symbol":"WWH",
            "price":"2,552.00",
            "change":"0.00",
            "pChg":"0.00"
         },
         {  
            "company":"Zoopla Property Group",
            "symbol":"ZPG",
            "price":"369.90",
            "change":"0.00",
            "pChg":"0.00"
         }
      ]
   },
   "coinranking":{  
      "exchange":"coinranking",
      "source":"https://coinranking.com",
      "time":"2018-03-18T23:04:55.702Z",
      "cached":false,
      "details":"https://coinranking.com/coin/",
      "data":[  
         {  
            "company":"Bitcoin",
            "symbol":"bitcoin-btc",
            "price":"8169.04",
            "change":215.54,
            "pChg":"2.71%"
         },
         {  
            "company":"Ethereum",
            "symbol":"ethereum-eth",
            "price":"531.28",
            "change":25.73,
            "pChg":"-4.62%"
         },
         {  
            "company":"Ripple",
            "symbol":"ripple-xrp",
            "price":"0.652",
            "change":0.01,
            "pChg":"1.89%"
         },
         {  
            "company":"Bitcoin Cash",
            "symbol":"bitcoin-cash-bch",
            "price":"927.90",
            "change":30.67,
            "pChg":"-3.20%"
         },
         {  
            "company":"Litecoin",
            "symbol":"litecoin-ltc",
            "price":"152.96",
            "change":1.19,
            "pChg":"-0.77%"
         },
         {  
            "company":"NEO",
            "symbol":"neo-neo",
            "price":"64.31",
            "change":2.63,
            "pChg":"4.26%"
         },
         {  
            "company":"Cardano",
            "symbol":"cardano-ada",
            "price":"0.156",
            "change":0,
            "pChg":"0.69%"
         },
         {  
            "company":"Stellar",
            "symbol":"stellar-xlm",
            "price":"0.218",
            "change":0.01,
            "pChg":"4.83%"
         },
         {  
            "company":"IOTA",
            "symbol":"iota-iot",
            "price":"1.23",
            "change":0.09,
            "pChg":"8.19%"
         },
         {  
            "company":"EOS",
            "symbol":"eos-eos",
            "price":"4.54",
            "change":0.15,
            "pChg":"-3.11%"
         },
         {  
            "company":"Monero",
            "symbol":"monero-xmr",
            "price":"202.26",
            "change":3.87,
            "pChg":"1.95%"
         },
         {  
            "company":"Dash",
            "symbol":"dash-dash",
            "price":"385.67",
            "change":1.39,
            "pChg":"-0.36%"
         },
         {  
            "company":"NEM",
            "symbol":"nem-xem",
            "price":"0.271",
            "change":0.01,
            "pChg":"-4.94%"
         },
         {  
            "company":"Tether",
            "symbol":"tether-usdt",
            "price":"1.00",
            "change":0,
            "pChg":"-0.16%"
         },
         {  
            "company":"TRON",
            "symbol":"tron-trx",
            "price":"0.0285",
            "change":0,
            "pChg":"0.23%"
         },
         {  
            "company":"VeChain",
            "symbol":"vechain-ven",
            "price":"3.63",
            "change":0.05,
            "pChg":"-1.49%"
         },
         {  
            "company":"Ethereum Classic",
            "symbol":"ethereum-classic-etc",
            "price":"16.62",
            "change":0.18,
            "pChg":"1.10%"
         },
         {  
            "company":"Lisk",
            "symbol":"lisk-lsk",
            "price":"12.08",
            "change":0.12,
            "pChg":"-1.01%"
         },
         {  
            "company":"Nano",
            "symbol":"nano-nano",
            "price":"8.18",
            "change":0.2,
            "pChg":"2.55%"
         },
         {  
            "company":"OmiseGo",
            "symbol":"omisego-omg",
            "price":"10.09",
            "change":0.19,
            "pChg":"1.90%"
         },
         {  
            "company":"Bitcoin Gold",
            "symbol":"bitcoin-gold-btg",
            "price":"57.51",
            "change":1.28,
            "pChg":"-2.18%"
         },
         {  
            "company":"QTUM",
            "symbol":"qtum-qtum",
            "price":"13.07",
            "change":0.62,
            "pChg":"-4.53%"
         },
         {  
            "company":"Binance Coin",
            "symbol":"binance-coin-bnb",
            "price":"8.73",
            "change":0.26,
            "pChg":"-2.91%"
         },
         {  
            "company":"ZCash",
            "symbol":"zcash-zec",
            "price":"237.06",
            "change":15.28,
            "pChg":"6.89%"
         },
         {  
            "company":"ICON",
            "symbol":"icon-icx",
            "price":"2.03",
            "change":0.06,
            "pChg":"2.96%"
         },
         {  
            "company":"Digix DAO",
            "symbol":"digix-dao-dgd",
            "price":"344.38",
            "change":20.7,
            "pChg":"-5.67%"
         },
         {  
            "company":"Populous",
            "symbol":"populous-ppt",
            "price":"14.77",
            "change":0.57,
            "pChg":"4.05%"
         },
         {  
            "company":"Steem",
            "symbol":"steem-steem",
            "price":"1.78",
            "change":0.03,
            "pChg":"-1.48%"
         },
         {  
            "company":"ByteCoin",
            "symbol":"bytecoin-bcn",
            "price":"0.00245",
            "change":0,
            "pChg":"1.81%"
         },
         {  
            "company":"Waves",
            "symbol":"waves-waves",
            "price":"4.39",
            "change":0.24,
            "pChg":"-5.28%"
         },
         {  
            "company":"Stratis",
            "symbol":"stratis-strat",
            "price":"4.34",
            "change":0.27,
            "pChg":"6.51%"
         },
         {  
            "company":"Verge",
            "symbol":"verge-xvg",
            "price":"0.0291",
            "change":0,
            "pChg":"1.31%"
         },
         {  
            "company":"Maker",
            "symbol":"maker-mkr",
            "price":"661.35",
            "change":7.36,
            "pChg":"-1.10%"
         },
         {  
            "company":"RChain",
            "symbol":"rchain-rhoc",
            "price":"1.02",
            "change":0.02,
            "pChg":"-1.76%"
         },
         {  
            "company":"Dogecoin",
            "symbol":"dogecoin-doge",
            "price":"0.00317",
            "change":0,
            "pChg":"-3.94%"
         },
         {  
            "company":"Siacoin",
            "symbol":"siacoin-sc",
            "price":"0.0107",
            "change":0,
            "pChg":"9.54%"
         },
         {  
            "company":"Decred",
            "symbol":"decred-dcr",
            "price":"50.76",
            "change":2.09,
            "pChg":"4.29%"
         },
         {  
            "company":"Status",
            "symbol":"status-snt",
            "price":"0.0987",
            "change":0.01,
            "pChg":"7.60%"
         },
         {  
            "company":"Bitshares",
            "symbol":"bitshares-bts",
            "price":"0.131",
            "change":0.01,
            "pChg":"-4.45%"
         },
         {  
            "company":"Augur",
            "symbol":"augur-rep",
            "price":"29.20",
            "change":1.6,
            "pChg":"-5.20%"
         },
         {  
            "company":"Bytom",
            "symbol":"bytom-btm",
            "price":"0.321",
            "change":0.01,
            "pChg":"-4.02%"
         },
         {  
            "company":"Aeternity",
            "symbol":"aeternity-ae",
            "price":"1.35",
            "change":0.15,
            "pChg":"-9.93%"
         },
         {  
            "company":"Ontology",
            "symbol":"ontology-ont",
            "price":"1.30",
            "change":0,
            "pChg":"0.02%"
         },
         {  
            "company":"Waltonchain",
            "symbol":"waltonchain-wtc",
            "price":"12.17",
            "change":0.24,
            "pChg":"2.04%"
         },
         {  
            "company":"Aion",
            "symbol":"aion-aion",
            "price":"2.56",
            "change":0.28,
            "pChg":"12.31%"
         },
         {  
            "company":"Zilliqa",
            "symbol":"zilliqa-zil",
            "price":"0.0396",
            "change":0,
            "pChg":"-3.19%"
         },
         {  
            "company":"Komodo",
            "symbol":"komodo-kmd",
            "price":"2.49",
            "change":0.09,
            "pChg":"-3.49%"
         },
         {  
            "company":"Ardor",
            "symbol":"ardor-ardr",
            "price":"0.253",
            "change":0.01,
            "pChg":"-3.50%"
         },
         {  
            "company":"Cryptonex",
            "symbol":"cryptonex-cnx",
            "price":"5.53",
            "change":0.06,
            "pChg":"1.03%"
         },
         {  
            "company":"ARK",
            "symbol":"ark-ark",
            "price":"2.40",
            "change":0.12,
            "pChg":"-4.77%"
         }
      ]
   }
};

 
module.exports = exchanges_3_static;